version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: embers-dolibarr_server_1
      APP_PORT: 80

  server:
    image: dolibarr/dolibarr:21
    restart: unless-stopped
    environment:
      DOLI_INSTALL_AUTO: "1"

      DOLI_DB_HOST: db
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
      DOLI_DB_TYPE: mysqli

      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}

      DOLI_URL_ROOT: http://localhost
      PHP_INI_DATE_TIMEZONE: Europe/Berlin

    volumes:
      - ${APP_DATA_DIR}/documents:/var/www/documents
      - ${APP_DATA_DIR}/custom:/var/www/html/custom

    depends_on:
      - db

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: ${DOLI_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOLI_DB_ROOT_PASSWORD}

    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql